services:
  app:
    build:
      context: .
      target: dev
    working_dir: /app
    ports:
      - "4321:4321"
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules/
        - action: sync
          path: ./public
          target: /app/public
        - action: sync
          path: ./astro.config.mjs
          target: /app/astro.config.mjs
        - action: sync
          path: ./tsconfig.json
          target: /app/tsconfig.json
        - action: rebuild
          path: ./package.json
          target: /app/package.json
